language: node_js
node_js:
  - "lts/*"
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
cache:
  bundler: true
  apt: true
  npm: true
  directories:
    - ~/.npm
    - .node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info
install:
  - npm ci
script:
  - npm run cy:run 
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true